// src/app/layout.tsx
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'
import { Suspense } from 'react'


// 💡 Import reusable components
import Header from '@/components/layouts/Header'
import Sidebar from '@/components/layouts/Sidebar'
import Footer from '@/components/layouts/Footer'

// 🛒 Cart Context
import { CartProvider } from '@/context/CartContext'

// Google Fonts
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'e commerce app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        <CartProvider>
          <Suspense fallback={null}>
            <Header />
          </Suspense>


          {/* Main Layout */}
          <div className="flex max-w-7xl mx-auto w-full mt-4 px-4">
            <Sidebar />
            <main className="flex-1">{children}</main>
          </div>

          <Footer />

          {/* ✅ Toast Notifications */}
          <Toaster
            position="top-center"
            richColors
            toastOptions={{
              classNames: {
                toast: 'w-[500px] max-w-[90%] shadow-lg text-center mx-auto',
              },
            }}
          />
        </CartProvider>
      </body>
    </html>
  )
}





